Выполнил задание на добавление режиссера
SAleksandrEr/java-filmorate pull request #14
Opened 2023-12-02 16:51 UTC by MishachS

2023-12-02 17:42 UTC, SAleksandrEr commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        genreStorage.createGenresFilm(film.getGenres(), film.getId());
есть предложение, или жанры с режиссёром добавить на уровне Dao или на уровне сервиса

2023-12-03 11:26 UTC, SAleksandrEr approved these changes

2023-12-03 15:59 UTC, RifatSuleymanov requested changes
1

2023-12-03 15:59 UTC, RifatSuleymanov approved these changes
1

2023-12-03 16:00 UTC, merged